#!/bin/bash

CONFIG=${BASH_SOURCE[0]}../config

OUT=$1
shift
TEST=$1
shift

BASE=${TEST/%.v3/}
exec $CONFIG/node --no-warnings --experimental-wasi-unstable-preview1 $CONFIG/wasi.node.mjs $OUT/${BASE}.wasm "$@"
