#!/usr/bin/env bash

CONFIG=${BASH_SOURCE[0]}../config

OUT=$1
shift
TEST=$1
shift

if [ "$VIRGIL_LOC" = "" ]; then
    VIRGIL_LOC=$OUT/../../
fi

BASE=${TEST/%.v3/}
exec $CONFIG/node --no-warnings --experimental-wasi-unstable-preview1 $CONFIG/wasi.node.mjs $OUT/${BASE}.wasm "$@"
